---
title: "MMI Assignment"
author: "Justin Pomeranz"
subtitle: "SOLUTION KEY"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = knitr::is_html_output())

library(readxl)
library(tidyverse)

site1 <- read_excel(here::here("data/MMI_HW_data.xlsx"),
                    sheet = "A75CC")
site2 <- read_excel(here::here("data/MMI_HW_data.xlsx"),
                    sheet = "A72")
other_sites <- read_excel(here::here("data/MMI_HW_data.xlsx"),
                        sheet = "other_sites")

taxa_info <- read_excel(here::here("data/MMI_HW_data.xlsx"),
                        sheet = "taxa_info")

site_info <- read_excel(here::here("data/MMI_HW_data.xlsx"),
                        sheet = "site_info")

all_sites <- bind_rows(site1, site2, other_sites)
all_sites <- left_join(all_sites, taxa_info)
```

## This is the KEY  

## Problem 1: ClingerTax  

```{r}
clng <- all_sites |>
  filter(Habit == "clinger") |>
  group_by(site_code) |>
  summarize(cling_tax = n()) |>
  mutate(s_cling = 100 * cling_tax / 20) |>
  select(-cling_tax)
clng
```

## Problem 2: IntolerantTax  

```{r}
intolTax <- all_sites |>
  group_by(site_code) |>
  filter(Bio2_sensitive == TRUE) |>
  summarise(n_sens = n()) |>
  mutate(s_intol = 100*n_sens / 21) |>
  select(site_code, s_intol)
intolTax
```


## Problem 3: PredatorTax  

```{r}
pred <- all_sites |>
  filter(FFG == "predator") |>
  group_by(site_code) |>
  summarize(pred_tax = n()) |>
  mutate(s_pred = 100 * pred_tax / 13) |>
  select(-pred_tax)
pred
```

## Problem 4: pi_ScraperTax  

```{r}
pi_scraper <- all_sites |>
  group_by(site_code) |>
  mutate(tot_n = sum(Count)) |>
  filter(FFG == "scraper") |>
  group_by(site_code, tot_n) |>
  summarise(n_scrape = sum(Count)) |>
  ungroup() |>
  mutate(pi_scrape = n_scrape / tot_n * 100,
         s_scrape = 100*pi_scrape / 44.2) |>
  select(site_code, s_scrape)
pi_scraper
```

## Problem 5: pi_EPTnoB  

```{r}
pi_no_b <- all_sites |>
  group_by(site_code) |>
  mutate(tot_n = sum(Count)) |>
  filter(Family != "Baetidae", 
         Order == "Ephemeroptera" |
           Order == "Plecoptera" |
           Order == "Trichoptera") |>
  group_by(site_code, tot_n) |>
  summarise(n_no_b = sum(Count)) |>
  ungroup() |>
  mutate(pi_no_b = n_no_b / tot_n * 100,
         s_pi_no_b = 100*pi_no_b / 79.3) |>
  select(site_code, s_pi_no_b)
pi_no_b
```

## Problem 6: Metrics from Tutorial  

```{r warning=FALSE}
total_tax <- all_sites |>
  distinct(site_code, Taxon) |>
  group_by(site_code) |>
  summarize(tot_tax = n()) |>
  mutate(s_total_tax = 100 * tot_tax / 42) |>
  select(-tot_tax)
total_tax

ept_tax <- all_sites |>
  filter(Order == "Ephemeroptera" |
           Order == "Plecoptera" |
           Order == "Trichoptera") |>
  distinct(site_code, Taxon) |>
  group_by(site_code) |>
  summarize(ept_tax = n())|>
  ungroup()|>
  mutate(s_ept_tax = 100 * ept_tax / 24.5) |>
  select(-ept_tax) 
ept_tax

pi_sens <- all_sites |>
  group_by(site_code) |>
  mutate(tot_n = sum(Count)) |>
  filter(sensitive_taxa == TRUE) |>
  group_by(site_code, tot_n, sensitive_taxa) |>
  summarise(n_sens = sum(Count)) |>
  ungroup() |>
  mutate(pi_sens = n_sens / tot_n * 100,
         s_pi_sens = 100*pi_sens / 72.3) |>
  select(site_code, s_pi_sens)
pi_sens

```

## Problem 7: Mean MMMI and site info 

```{r}
mmi_scores <- left_join(total_tax, ept_tax)
mmi_scores <- left_join(mmi_scores, pi_sens)
mmi_scores <- left_join(mmi_scores, pi_no_b)
mmi_scores <- left_join(mmi_scores, clng)
mmi_scores <- left_join(mmi_scores, intolTax)
mmi_scores <- left_join(mmi_scores, pred)
mmi_scores <- left_join(mmi_scores, pi_scraper)
mmi_mean <- mmi_scores |>
  rowwise() |>
  mutate(mmi_mean = mean(c_across(s_total_tax:s_pred))) |>
  select(site_code, mmi_mean)
mmi_mean <- left_join(mmi_mean, site_info)
mmi_mean
```


## Problem 8: Pairwise plots  

```{r}
mmi_mean |>
  filter(!is.na(pairwise)) |>
  ggplot(aes(x = impact_category,
             y = mmi_mean,
             fill = impact_category)) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = 48)) +
  geom_hline(aes(yintercept = 40)) +
  facet_wrap(~pairwise)
```


## Problem 9: Longitudinal plots  

```{r}
mmi_mean |>
  filter(!is.na(distance)) |>
  ggplot(aes(x = distance,
             y = mmi_mean,
             fill = impact_category)) +
  geom_bar(stat = "identity")  +
  geom_hline(aes(yintercept = 48)) +
  geom_hline(aes(yintercept = 40))
```

